"""Alert model for dashboard notifications."""

from datetime import datetime
from typing import Optional
from sqlalchemy import String, Text, DateTime, Boolean, JSON, ForeignKey, Integer
from sqlalchemy.orm import Mapped, mapped_column

from database import Base


class Alert(Base):
    """Alert generated by analysis modules."""

    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Alert classification
    alert_type: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    # Types: 'arbitrage', 'volume_spike', 'spread_alert', 'mm_pullback', 'whale_trade'

    severity: Mapped[str] = mapped_column(String(20), default="info")
    # Severity: 'info', 'medium', 'high'

    # Alert content
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Related market (optional - some alerts span multiple markets)
    market_id: Mapped[Optional[str]] = mapped_column(
        String(255),
        ForeignKey("markets.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # For cross-market alerts (e.g., arbitrage)
    related_market_ids: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)

    # Detailed data (JSON blob with analysis results)
    data: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)

    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, index=True)
    dismissed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True, index=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, index=True)
    expires_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    def __repr__(self) -> str:
        return f"<Alert [{self.severity}] {self.alert_type}: {self.title}>"

    def dismiss(self) -> None:
        """Mark alert as dismissed."""
        self.is_active = False
        self.dismissed_at = datetime.utcnow()

    @classmethod
    def create_arbitrage_alert(
        cls,
        title: str,
        description: str,
        market_ids: list,
        profit_estimate: float,
        data: dict,
    ) -> "Alert":
        """Factory method for arbitrage alerts."""
        return cls(
            alert_type="arbitrage",
            severity="high" if profit_estimate > 0.05 else "medium",
            title=title,
            description=description,
            related_market_ids=market_ids,
            data={**data, "profit_estimate": profit_estimate},
        )

    @classmethod
    def create_volume_alert(
        cls,
        market_id: str,
        title: str,
        volume_ratio: float,
        data: dict,
    ) -> "Alert":
        """Factory method for volume spike alerts."""
        severity = "high" if volume_ratio > 5 else "medium" if volume_ratio > 3 else "info"
        return cls(
            alert_type="volume_spike",
            severity=severity,
            title=title,
            description=f"Volume is {volume_ratio:.1f}x normal levels",
            market_id=market_id,
            data={**data, "volume_ratio": volume_ratio},
        )

    @classmethod
    def create_spread_alert(
        cls,
        market_id: str,
        title: str,
        spread_pct: float,
        data: dict,
    ) -> "Alert":
        """Factory method for spread alerts."""
        return cls(
            alert_type="spread_alert",
            severity="medium" if spread_pct > 0.05 else "info",
            title=title,
            description=f"Spread is {spread_pct*100:.1f}%",
            market_id=market_id,
            data={**data, "spread_pct": spread_pct},
        )

    @classmethod
    def create_mm_pullback_alert(
        cls,
        market_id: str,
        title: str,
        data: dict,
    ) -> "Alert":
        """Factory method for market maker pullback alerts."""
        return cls(
            alert_type="mm_pullback",
            severity="high",
            title=title,
            description="Market makers appear to be reducing liquidity",
            market_id=market_id,
            data=data,
        )
